version: "3.8"

services:
  any-travel-api:
    build:
      context: ./api
    container_name: any-travel-api
    command: pm2-runtime process.yaml
    environment:
      - DOCKER=true
    expose:
      - 9000
    restart: always
    links:
      - any-travel-db
    ports:
      - "9000:9000"

  any-travel-db:
    container_name: any-travel-db
    image: mongo
    command: mongod --port 27000
    expose:
      - 27000
    ports:
      - "27000:27000"

  any-travel-app:
    build:
      context: ./app
    container_name: any-travel-app
    expose:
      - 80
    ports:
      - "80:80"

