version: "3.8"

services:
  any-travel-api:
    build:
      context: ./api
    container_name: any-travel-api
    command: pm2-runtime process.yaml
    expose:
      - 9000
    restart: always
    links:
      - mongo-db
    ports:
      - "9000:9000"

  any-travel-db:
    container_name: any-travel-db
    image: mongo
    ports:
      - "27017:27017"

  any-travel-app:
    build:
      context: ./app
    container_name: any-travel-app
    expose:
      - 80
    ports:
      - "4200:80"

