export enum WizardStep {
  STEP_NONE = 'NONE',
  STEP_SELECT_GROUP = 'SELECT_GROUP',
  STEP_SELECT_ATTRACTIONS = 'SELECT_ATTRACTIONS',
  STEP_ADD_DESTINATION = 'ADD_DESTINATION',
  STEP_ADD_DETAILS = 'ADD_DETAILS',
  STEP_FINISH = 'FINISH'
}
