version: '3.8'

services:
 back:
  build:
   context: .
   target: api-build
  container_name: back
  command: pm2-runtime process.yaml
  expose:
    - 9000
  restart: always
  links:
    - mongo-db
  ports:
    - "9000:9000"

 mongo-db:
  container_name: mongo-db
  image: mongo
  ports:
    - "27017:27017"